const fs = require('fs');

const path = 'c:\\Users\\sriva\\Documents\\Work\\Coding\\BharatOne\\src\\data\\pune.js';
let content = fs.readFileSync(path, 'utf8');

// The file defines `const puneMetro = { ... };\n\nexport default puneMetro;`
// Let's extract the JSON part
const startIdx = content.indexOf('{');
const endIdx = content.lastIndexOf(';');
const endBraceIdx = content.lastIndexOf('}', endIdx);

let jsonStr = content.substring(startIdx - 1, endBraceIdx + 1);
// Fix the non-quoted keys generated by replacing it back if needed, 
// Or better just use `eval`.
let puneMetro;
try {
    eval(`puneMetro = ${jsonStr};`);
} catch (e) {
    console.error("Eval failed", e);
    process.exit(1);
}

// 1. Update colors
puneMetro.lines[0].color = '#903373';
puneMetro.lines[0].colorLight = '#C774A8';
puneMetro.lines[1].color = '#007CB0';
puneMetro.lines[1].colorLight = '#4DAAE0';

// 2. Add Line 3
const line3Stations = [
    "Megapolis Circle", "Embassy Quadron Business Park", "Dohler", "Infosys Phase II",
    "Wipro Phase II", "Pall India", "Shivaji Chowk", "Hinjawadi", "Wakad Chowk",
    "Balewadi Stadium", "NICMAR", "Ram Nagar", "Laxmi Nagar", "Balewadi Phata",
    "Baner Gaon", "Baner", "Krushi Anusadhan", "Sakal Nagar", "University",
    "R.B.I.", "Agriculture College", "Shivaji Nagar", "Civil Court"
];

const intermap = {
    'Shivaji Nagar': ['purple'],
    'Civil Court': ['purple', 'aqua']
};

const createStation = (idPrefix, index, name) => {
    const isInterchange = intermap[name] !== undefined;
    const interchangeWith = intermap[name] || [];
    return {
        id: `${idPrefix}${String(index + 1).padStart(2, '0')}`,
        name: name,
        nameLocal: '',
        type: 'elevated',
        isInterchange,
        interchangeWith,
        landmark: name,
        zone: 1, // Phase 3 / Line 3 zone
        contact: '18002700540',
        parking: true,
        facilities: ['First Aid Box', 'CCTV', 'Restrooms', 'Drinking Water', 'Lifts / Escalators'],
        platforms: [
            { no: 1, towards: 'Terminal 1' },
            { no: 2, towards: 'Terminal 2' }
        ],
        gates: [
            { gate: 'A', landmarks: ['Main Road Entrance', 'Bus Stop'] },
            { gate: 'B', landmarks: ['Residential Area Exit'] }
        ]
    };
};

const line3Data = line3Stations.map((s, i) => createStation('r', i, s));

puneMetro.lines.push({
    id: "line3",
    name: "Line 3 (Hinjewadi)",
    color: "#D81B60",
    colorLight: "#F06292",
    corridor: "Line 3",
    length: "23.3 km",
    totalStations: 23,
    status: "construction", // It's upcoming. The map handles non-operational lines as dashes.
    stations: line3Data
});

// Update interchange pointers for purple and aqua
puneMetro.lines[0].stations.forEach(s => {
    if (s.name === 'Shivaji Nagar') {
        s.isInterchange = true;
        if (!s.interchangeWith.includes('line3')) s.interchangeWith.push('line3');
    }
    if (s.name === 'Civil Court') {
        s.isInterchange = true;
        if (!s.interchangeWith.includes('line3')) s.interchangeWith.push('line3');
    }
});
puneMetro.lines[1].stations.forEach(s => {
    if (s.name === 'Civil Court') {
        s.isInterchange = true;
        if (!s.interchangeWith.includes('line3')) s.interchangeWith.push('line3');
    }
});

puneMetro.totalLines = 3;
puneMetro.totalStations = 14 + 16 + 23; // roughly 53
puneMetro.totalLength = "56.5 km";

const finalContent = `/**
 * Pune Metro Rail — Complete Station & Line Data
 * Source: Official Data & Upcoming Phase
 */

const puneMetro = ${JSON.stringify(puneMetro, null, 4).replace(/"([^"]+)":/g, '$1:')};

export default puneMetro;
`;

fs.writeFileSync(path, finalContent, 'utf8');
console.log('Update successful!');
